version: "3.7"
services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data:Z

    ports:
      - ${OUT_PORT}:${IN_PORT}
    environment:
      - node.name=elasticsearch
      - ES_JAVA_OPTS=-${XMS} -${XMX}
      - discovery.type=single-node
    networks:
      - elk
    restart: unless-stopped

volumes:
  elasticsearch:
networks:
  elk:
    driver: bridge
